project:
  type: book
  preview:
    port: 7777
  resources:
    - "assets/**"

execute:
  freeze: auto

book:
  title: "The Conjoint Cookbook"
  subtitle: "A practical, interdisciplinary guide to designing, fielding, and analyzing choice experiments with R"
  author:
  - name: Andrew Heiss
    affiliation: Georgia State University
    url: https://www.andrewheiss.com
    orcid: 0000-0002-3948-3914
  - name: John Paul Helveston
    affiliation: George Washington University
    url: https://www.jhelvy.com/
    orcid: 0000-0002-2657-9191
  date: "2025-08-26"

  site-url: "https://andrewheiss.github.io/conjoint-cookbook/"

  repo-url: "https://github.com/andrewheiss/golden-gorilla"
  repo-actions: [source, issue]

  page-navigation: true

  sidebar: 
    logo: /img/logo.png
    logo-alt: The Conjoint Cookbook hex logo
    search: true
    style: docked

  chapters:
    - part: "Introduction"
      chapters:
        - index.qmd
        - mms-amces.qmd
        - utils-preds.qmd
    - part: "Designing"
      chapters:
        - index.qmd
    - part: "Fielding"
      chapters:
        - index.qmd
        - process-reshape-data.qmd
    - part: "Analyzing: causal effects"
      chapters:
        - mms-amces-ols.qmd
        - mms-amces-multinomial.qmd
        - mms-amces-bayes.qmd
    - part: "Analyzing: preference descriptions"
      chapters:
        - utils-preds-freq.qmd
        - utils-preds-bayes.qmd
    - part: "Final things"
      chapters:
        - index.qmd

format:
  html:
    # code-link: true  # This is neat, but goes kinda slow
    toc-title: On this page

    filters:
      - output-styling
    output-styling:
      appearance: default

    highlight-style: atom-one
    theme:
      - zephyr
      - html/custom.scss
    include-in-header: 
      - text: |
          <link rel="preload" href="assets/fonts/AfacadFlux-VariableFont_slnt,wght.ttf" as="font" type="font/ttf" crossorigin>
          <link rel="preload" href="assets/fonts/LibreFranklin-VariableFont_wght.ttf" as="font" type="font/ttf" crossorigin>
          <link rel="preload" href="assets/fonts/LibreFranklin-Italic-VariableFont_wght.ttf" as="font" type="font/ttf" crossorigin>

    fig-width: 6
    fig-height: 3.708  # 6 * 0.618
    fig-align: center

    knitr:
      opts_chunk:
        dev: "ragg_png"
        dpi: 300
        out-width: "90%"
        R.options:
          digits: 4
          width: 200
          knitr.graphics.auto_pdf: true
