---
title: "Tutorial on conjoint experiments"
format: 
  gfm: 
    wrap: preserve
---

<!-- README.md is generated from README.qmd. Please edit that file -->

```{r setup, include=FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>",
  fig.path = "README-",
  fig.retina = 3
)

library(emoji)
```

[Andrew Heiss](https://www.andrewheiss.com/) • Andrew Young School of Policy Studies • Georgia State University

## `r emoji_glue(":1st_place_medal::gorilla:")`: Note on "golden gorilla" project name

Because project titles change all the time with revisions, rewriting, and peer review, I used [{codename}](http://svmiller.com/codename/) to generate an [Ubuntu-style](https://wiki.ubuntu.com/DevelopmentCodeNames) internal-to-me project name that won’t change.

```{r generate-code-name, eval=FALSE}
library(codename)
codename_message()
#> code name generated by {codename} v.0.5.0. R version 4.4.1 (2024-06-14).

codename(seed = "conjoint psych", type = "ubuntu")
#> [1] "golden gorilla"
```
