{
  "hash": "61c446d69758055cdc9a699615283ff9",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"Causal estimands\"\nsubtitle: \"Marginal means (MMs) and average marginal component effects (AMCEs)\"\nformat:\n  html:\n    code-fold: true\n---\n\n\n\n## Building the intuition for marginal means, differences in marginal means, and regression coefficients\n\n### Marginal means\n\nAt its core, a \"marginal mean\" refers to the literal mean in the margins in a contingency table of model predictions based on a balanced grid of predictors.\n\nTo illustrate, we'll make a model that predicts penguin weight based on species and sex and then make predictions for a balanced grid of covariates (i.e. male Adelie, female Adelie, male Chinstrap, female Chinstrap, male Gentoo, female Gentoo):\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(tidyverse)\nlibrary(marginaleffects)\n```\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"show\"}\npenguins <- penguins |> drop_na(sex)\n\nmodel <- lm(body_mass ~ species + sex, data = penguins)\n\npreds <- model |> \n  predictions(datagrid(species = unique, sex = unique))\n```\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\npreds |>\n  select(estimate, species, sex) |>\n  pivot_wider(names_from = sex, values_from = estimate) |>\n  select(Species = species, Female = female, Male = male) |>\n  tt(\n    notes = \"Predicted penguin weights (g) from model `lm(body_mass ~ species + sex)`\"\n  ) |>\n  group_tt(\n    j = list(\"Sex\" = 2:3)\n  ) |>\n  format_tt(\"notes\", markdown = TRUE) |>\n  style_tt(j = 2:3, align = \"c\")\n```\n\n::: {.cell-output-display}\n\\begin{table}\n\\centering\n\\begin{talltblr}[         %% tabularray outer open\nentry=none,label=none,\nnote{}={Predicted penguin weights (g) from model \\texttt{lm(body\\_mass \\textasciitilde{} species + sex)}},\n]                     %% tabularray outer close\n{                     %% tabularray inner open\ncolspec={Q[]Q[]Q[]},\ncolumn{3}={}{halign=c,},\ncell{1}{2}={c=2,}{halign=c, halign=c,},\ncell{2-5}{2}={}{halign=c,},\n}                     %% tabularray inner close\n\\toprule\n& Sex &  \\\\ \\cmidrule[lr]{2-3}\nSpecies & Female & Male \\\\ \\midrule %% TinyTableHeader\nAdelie & 3372.387 & 4039.942 \\\\\nGentoo & 4750.245 & 5417.800 \\\\\nChinstrap & 3399.311 & 4066.866 \\\\\n\\bottomrule\n\\end{talltblr}\n\\end{table}\n:::\n:::\n\n\nWe can add a column and row in the margins to show the species-specific and sex-specific average predicted weights. For the sex-specific averages, all the between-species variation is \"marginalized out\" or accounted for. For the species-specific averages, all the between-sex variation is similarly marginalized out:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmean_sex <- preds |>\n  group_by(sex) |>\n  mutate(avg_estimate = mean(estimate)) |>\n  select(species, sex, estimate, avg_estimate) |>\n  pivot_wider(names_from = species, values_from = estimate) |>\n  mutate(\n    avg_explanation = glue::glue(\n      \"{round(avg_estimate, 0)}<br>\",\n      \"<span style='font-size:70%'>\",\n      \"({round(Adelie, 0)} + {round(Chinstrap, 0)} + {round(Gentoo, 0)}) / 3\",\n      \"</span>\"\n    )\n  ) |>\n  select(sex, avg_explanation) |>\n  mutate(species = \"Marginal mean\") |>\n  pivot_wider(names_from = sex, values_from = avg_explanation)\n\nmean_species <- preds |>\n  group_by(species) |>\n  summarize(avg_estimate = mean(estimate))\n\nall_combined <- preds |>\n  ungroup() |>\n  select(estimate, species, sex) |>\n  pivot_wider(names_from = sex, values_from = estimate) |>\n  left_join(mean_species, by = join_by(species)) |>\n  arrange(species) |>\n  mutate(\n    avg_explanation = glue::glue(\n      \"{round(avg_estimate, 0)}<br>\",\n      \"<span style='font-size:70%'>\",\n      \"({round(female, 0)} + {round(male, 0)}) / 2\",\n      \"</span>\"\n    )\n  ) |>\n  mutate(across(c(female, male), ~ as.character(round(., 0)))) |>\n  select(-avg_estimate) |>\n  bind_rows(mean_sex)\n\nall_combined |>\n  select(\n    Species = species,\n    Female = female,\n    Male = male,\n    `Marginal mean` = avg_explanation\n  ) |>\n  tt(\n    notes = \"Predicted penguin weights (g) from model `lm(body_mass ~ species + sex)`\"\n  ) |>\n  group_tt(\n    j = list(\"Sex\" = 2:3)\n  ) |>\n  format_tt(replace = \"\") |>\n  format_tt(\"notes\", markdown = TRUE) |>\n  style_tt(j = 2:4, align = \"c\") |>\n  style_tt(i = 4, line = \"t\") |>\n  theme_html(i = 4, css = \"border-top-style: dashed;\") |>\n  style_tt(i = 1:4, j = 3, line = \"r\") |>\n  theme_html(j = 3, css = \"border-right-style: dashed;\")\n```\n\n::: {.cell-output-display}\n\\begin{table}\n\\centering\n\\begin{talltblr}[         %% tabularray outer open\nentry=none,label=none,\nnote{}={Predicted penguin weights (g) from model \\texttt{lm(body\\_mass \\textasciitilde{} species + sex)}},\n]                     %% tabularray outer close\n{                     %% tabularray inner open\ncolspec={Q[]Q[]Q[]Q[]},\ncolumn{3-4}={}{halign=c,},\ncell{1}{2}={c=2,}{halign=c, halign=c,},\ncell{2-6}{2}={}{halign=c,},\nhline{6}={1-2,4}{solid, black, 0.1em},\nvline{4}={3-6}{solid, black, 0.1em},\n}                     %% tabularray inner close\n\\toprule\n& Sex &  &  \\\\ \\cmidrule[lr]{2-3}\nSpecies & Female & Male & Marginal mean \\\\ \\midrule %% TinyTableHeader\nAdelie & 3372 & 4040 & 3706<br><span style='font-size:70%'>(3372 + 4040) / 2</span> \\\\\nChinstrap & 3399 & 4067 & 3733<br><span style='font-size:70%'>(3399 + 4067) / 2</span> \\\\\nGentoo & 4750 & 5418 & 5084<br><span style='font-size:70%'>(4750 + 5418) / 2</span> \\\\\nMarginal mean & 3841<br><span style='font-size:70%'>(3372 + 3399 + 4750) / 3</span> & 4508<br><span style='font-size:70%'>(4040 + 4067 + 5418) / 3</span> &   \\\\\n\\bottomrule\n\\end{talltblr}\n\\end{table}\n:::\n:::\n\n\n\n\n### Differences in marginal means\n\nBecause regression is just fancy averages, the differences in marginal means here are actually identical to the coefficients in regression model. For instance, here are the results from the model:\n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"show\"}\nmodel |> broom::tidy()\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 4 x 5\n  term             estimate std.error statistic   p.value\n  <chr>               <dbl>     <dbl>     <dbl>     <dbl>\n1 (Intercept)        3372.       31.4   107.    4.34e-258\n2 speciesChinstrap     26.9      46.5     0.579 5.63e-  1\n3 speciesGentoo      1378.       39.1    35.2   1.05e-113\n4 sexmale             668.       34.7    19.2   8.73e- 56\n```\n\n\n:::\n:::\n\n\nThe `sexmale` coefficient of 667.56 represents the effect of moving from male to female when species is held constant.\n\nThe marginal means table shows the same thing. Marginalizing over species (i.e. holding species constant), the average predicted weight for female penguins is 3840.6 and for male penguins is 4508.2. The difference in those marginal means is 667.56—identical to the `sexmale` coefficient! \n\n\n::: {.cell}\n\n```{.r .cell-code}\namce_species <- preds |>\n  group_by(species) |>\n  summarize(avg_estimate = mean(estimate)) |>\n  mutate(amce = avg_estimate - avg_estimate[1]) |>\n  mutate(\n    amce_nice = glue::glue(\n      \"{round(amce, 0)}<br>\",\n      \"<span style='font-size:70%'>\",\n      \"{species} − {species[1]}, or<br>\",\n      \"{round(avg_estimate, 0)} − {round(avg_estimate[1], 0)}\",\n      \"</span>\"\n    )\n  ) |>\n  select(species, amce_nice)\n\namce_sex <- preds |>\n  group_by(sex) |>\n  summarize(avg_estimate = mean(estimate)) |>\n  mutate(amce = avg_estimate - avg_estimate[1]) |>\n  mutate(\n    amce_nice = glue::glue(\n      \"{round(amce, 0)}<br>\",\n      \"<span style='font-size:70%'>\",\n      \"{sex} − {sex[1]}, or<br>\",\n      \"{round(avg_estimate, 0)} − {round(avg_estimate[1], 0)}\",\n      \"</span>\"\n    )\n  ) |>\n  select(sex, amce_nice) |>\n  mutate(species = \"∆ in marginal mean\") |>\n  pivot_wider(names_from = sex, values_from = amce_nice)\n```\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nall_combined |>\n  left_join(amce_species, by = join_by(species)) |>\n  bind_rows(amce_sex) |>\n  select(\n    Species = species,\n    Female = female,\n    Male = male,\n    `Marginal mean` = avg_explanation,\n    `∆ in marginal mean` = amce_nice\n  ) |>\n  tt(\n    notes = \"Predicted penguin weights (g) from model `lm(body_mass ~ species + sex)`\"\n  ) |>\n  group_tt(\n    j = list(\"Sex\" = 2:3)\n  ) |>\n  format_tt(replace = \"\") |>\n  format_tt(\"notes\", markdown = TRUE) |>\n  style_tt(j = 2:5, align = \"c\") |>\n  style_tt(i = 4, line = \"t\") |>\n  theme_html(i = 4, css = \"border-top-style: dashed;\") |>\n  style_tt(i = 1:5, j = 3, line = \"r\") |>\n  theme_html(j = 3, css = \"border-right-style: dashed;\")\n```\n\n::: {.cell-output-display}\n\\begin{table}\n\\centering\n\\begin{talltblr}[         %% tabularray outer open\nentry=none,label=none,\nnote{}={Predicted penguin weights (g) from model \\texttt{lm(body\\_mass \\textasciitilde{} species + sex)}},\n]                     %% tabularray outer close\n{                     %% tabularray inner open\ncolspec={Q[]Q[]Q[]Q[]Q[]},\ncolumn{3-5}={}{halign=c,},\ncell{1}{2}={c=2,}{halign=c, halign=c,},\ncell{2-7}{2}={}{halign=c,},\nhline{6}={1-2,4-5}{solid, black, 0.1em},\nvline{4}={3-7}{solid, black, 0.1em},\n}                     %% tabularray inner close\n\\toprule\n& Sex &  &  &  \\\\ \\cmidrule[lr]{2-3}\nSpecies & Female & Male & Marginal mean & ∆ in marginal mean \\\\ \\midrule %% TinyTableHeader\nAdelie & 3372 & 4040 & 3706<br><span style='font-size:70%'>(3372 + 4040) / 2</span> & 0<br><span style='font-size:70%'>Adelie − Adelie, or<br>3706 − 3706</span> \\\\\nChinstrap & 3399 & 4067 & 3733<br><span style='font-size:70%'>(3399 + 4067) / 2</span> & 27<br><span style='font-size:70%'>Chinstrap − Adelie, or<br>3733 − 3706</span> \\\\\nGentoo & 4750 & 5418 & 5084<br><span style='font-size:70%'>(4750 + 5418) / 2</span> & 1378<br><span style='font-size:70%'>Gentoo − Adelie, or<br>5084 − 3706</span> \\\\\nMarginal mean & 3841<br><span style='font-size:70%'>(3372 + 3399 + 4750) / 3</span> & 4508<br><span style='font-size:70%'>(4040 + 4067 + 5418) / 3</span> &   &   \\\\\n∆ in marginal mean & 0<br><span style='font-size:70%'>female − female, or<br>3841 − 3841</span> & 668<br><span style='font-size:70%'>male − female, or<br>4508 − 3841</span> &   &   \\\\\n\\bottomrule\n\\end{talltblr}\n\\end{table}\n:::\n:::\n\n\n**Differences in marginal means are equivalent to marginal effects or regression coefficients.** \n\n### Faster way with {marginaleffects}\n\nThese manual calculations are a pain though. We can use {marginaleffects} to do it more directly:\n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"show\"}\navg_predictions(model, \n  newdata = datagrid(species = unique, sex = unique),\n  by = c(\"sex\", \"species\")\n)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n    sex   species Estimate Std. Error     z Pr(>|z|)   S 2.5 % 97.5 %\n female Adelie        3372       31.4 107.3   <0.001 Inf  3311   3434\n female Chinstrap     3399       42.1  80.7   <0.001 Inf  3317   3482\n female Gentoo        4750       34.0 139.5   <0.001 Inf  4684   4817\n male   Adelie        4040       31.4 128.5   <0.001 Inf  3978   4102\n male   Chinstrap     4067       42.1  96.5   <0.001 Inf  3984   4149\n male   Gentoo        5418       33.6 161.3   <0.001 Inf  5352   5484\n\nType: response\n```\n\n\n:::\n\n```{.r .cell-code  code-fold=\"show\"}\navg_comparisons(model, \n  newdata = datagrid(species = unique, sex = unique)\n)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n    Term           Contrast Estimate Std. Error      z Pr(>|z|)     S  2.5 %\n sex     male - female         667.6       34.7 19.236   <0.001 271.5  599.5\n species Chinstrap - Adelie     26.9       46.5  0.579    0.562   0.8  -64.2\n species Gentoo - Adelie      1377.9       39.1 35.236   <0.001 901.1 1301.2\n 97.5 %\n    736\n    118\n   1455\n\nType: response\n```\n\n\n:::\n:::\n\n\n## Conjoint designs, marginal means, and AMCEs\n\nMarginal means in conjoints represent the probability-scale fitted values from the model, calculated across a balanced reference grid of all possible combinations of feature levels. These predictions are then marginalized or averaged across features of interest and result in causal estimands like the AMCE.\n\nIn the case of the sticker experiment, there are 12 possible combinations of price, packaging, and flavor:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nstickers <- readRDS(\"data/processed_data/study_5_sticker.rds\")\n\nmodel_ols <- lm(\n  choice ~ price + packaging + flavor,\n  data = stickers\n)\n```\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nfeature_grid <- stickers |> \n  tidyr::expand(price, packaging, flavor)\ntt(feature_grid)\n```\n\n::: {.cell-output-display}\n\\begin{table}\n\\centering\n\\begin{tblr}[         %% tabularray outer open\n]                     %% tabularray outer close\n{                     %% tabularray inner open\ncolspec={Q[]Q[]Q[]},\n}                     %% tabularray inner close\n\\toprule\nprice & packaging & flavor \\\\ \\midrule %% TinyTableHeader\n$2 & Plastic + paper & Chocolate \\\\\n$2 & Plastic + paper & Nuts \\\\\n$2 & Plastic + sticker & Chocolate \\\\\n$2 & Plastic + sticker & Nuts \\\\\n$3 & Plastic + paper & Chocolate \\\\\n$3 & Plastic + paper & Nuts \\\\\n$3 & Plastic + sticker & Chocolate \\\\\n$3 & Plastic + sticker & Nuts \\\\\n$4 & Plastic + paper & Chocolate \\\\\n$4 & Plastic + paper & Nuts \\\\\n$4 & Plastic + sticker & Chocolate \\\\\n$4 & Plastic + sticker & Nuts \\\\\n\\bottomrule\n\\end{tblr}\n\\end{table}\n:::\n:::\n\n\nWe can feed each row of this balanced grid into the model to generate 12 predicted values:\n\n\n::: {.cell}\n\n```{.r .cell-code}\npredictions(model_ols, newdata = feature_grid)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n Estimate Std. Error     z Pr(>|z|)     S  2.5 % 97.5 %\n   0.8003     0.0115 69.39   <0.001   Inf 0.7777 0.8229\n   0.3933     0.0115 34.10   <0.001 844.2 0.3707 0.4159\n   0.9153     0.0115 79.39   <0.001   Inf 0.8927 0.9379\n   0.5082     0.0115 44.07   <0.001   Inf 0.4856 0.5308\n   0.6565     0.0115 56.91   <0.001   Inf 0.6339 0.6791\n   0.2495     0.0115 21.63   <0.001 342.4 0.2269 0.2721\n   0.7715     0.0115 66.88   <0.001   Inf 0.7489 0.7941\n   0.3645     0.0115 31.59   <0.001 725.3 0.3419 0.3871\n   0.4815     0.0115 41.73   <0.001   Inf 0.4589 0.5042\n   0.0745     0.0115  6.46   <0.001  33.2 0.0519 0.0971\n   0.5965     0.0115 51.71   <0.001   Inf 0.5739 0.6191\n   0.1895     0.0115 16.43   <0.001 199.2 0.1669 0.2121\n\nType: response\n```\n\n\n:::\n:::\n\n\nFinally, we can marginalize or average these predicted values across features of interest. For instance, to find the marginal means for the two packaging conditions, we can calculate the group averages for the two types of packaging:\n\n\n::: {.cell}\n\n```{.r .cell-code}\npredictions(model_ols, newdata = feature_grid) |> \n  group_by(packaging) |> \n  summarize(avg = mean(estimate))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 2 x 2\n  packaging           avg\n  <fct>             <dbl>\n1 Plastic + paper   0.443\n2 Plastic + sticker 0.558\n```\n\n\n:::\n:::\n\n\nManually creating a balanced reference grid and using `group_by()` and `summarize()` is useful for understanding the intuition behind finding estimated marginal means, but in practice it is better to use `avg_predictions()` from {marginaleffects}, which (1) creates the balanced grid automatically, (2) provides standard errors and other estimates of uncertainty, and (3) can adjust the standard errors to account for repeated respondents:\n\n\n::: {.cell}\n\n```{.r .cell-code}\navg_predictions(\n  model_ols,\n  newdata = \"balanced\",\n  by = \"packaging\",\n  vcov = ~resp_id\n)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n         packaging Estimate Std. Error    z Pr(>|z|)   S 2.5 % 97.5 %\n Plastic + paper      0.443    0.00868 51.0   <0.001 Inf 0.426  0.460\n Plastic + sticker    0.558    0.00881 63.3   <0.001 Inf 0.540  0.575\n\nType: response\n```\n\n\n:::\n:::\n\n",
    "supporting": [
      "mms-amces_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {
      "knitr": [
        "{\"type\":\"list\",\"attributes\":{\"knit_meta_id\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\"]}},\"value\":[{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"float\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"tabularray\"]},{\"type\":\"NULL\"},{\"type\":\"character\",\"attributes\":{},\"value\":[\"\\\\usepackage[normalem]{ulem}\",\"\\\\usepackage{graphicx}\",\"\\\\usepackage{rotating}\",\"\\\\UseTblrLibrary{booktabs}\",\"\\\\UseTblrLibrary{siunitx}\",\"\\\\NewTableCommand{\\\\tinytableDefineColor}[3]{\\\\definecolor{#1}{#2}{#3}}\",\"\\\\newcommand{\\\\tinytableTabularrayUnderline}[1]{\\\\underline{#1}}\",\"\\\\newcommand{\\\\tinytableTabularrayStrikeout}[1]{\\\\sout{#1}}\"]}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"float\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"tabularray\"]},{\"type\":\"NULL\"},{\"type\":\"character\",\"attributes\":{},\"value\":[\"\\\\usepackage[normalem]{ulem}\",\"\\\\usepackage{graphicx}\",\"\\\\usepackage{rotating}\",\"\\\\UseTblrLibrary{booktabs}\",\"\\\\UseTblrLibrary{siunitx}\",\"\\\\NewTableCommand{\\\\tinytableDefineColor}[3]{\\\\definecolor{#1}{#2}{#3}}\",\"\\\\newcommand{\\\\tinytableTabularrayUnderline}[1]{\\\\underline{#1}}\",\"\\\\newcommand{\\\\tinytableTabularrayStrikeout}[1]{\\\\sout{#1}}\"]}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"float\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"tabularray\"]},{\"type\":\"NULL\"},{\"type\":\"character\",\"attributes\":{},\"value\":[\"\\\\usepackage[normalem]{ulem}\",\"\\\\usepackage{graphicx}\",\"\\\\usepackage{rotating}\",\"\\\\UseTblrLibrary{booktabs}\",\"\\\\UseTblrLibrary{siunitx}\",\"\\\\NewTableCommand{\\\\tinytableDefineColor}[3]{\\\\definecolor{#1}{#2}{#3}}\",\"\\\\newcommand{\\\\tinytableTabularrayUnderline}[1]{\\\\underline{#1}}\",\"\\\\newcommand{\\\\tinytableTabularrayStrikeout}[1]{\\\\sout{#1}}\"]}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"float\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"tabularray\"]},{\"type\":\"NULL\"},{\"type\":\"character\",\"attributes\":{},\"value\":[\"\\\\usepackage[normalem]{ulem}\",\"\\\\usepackage{graphicx}\",\"\\\\usepackage{rotating}\",\"\\\\UseTblrLibrary{booktabs}\",\"\\\\UseTblrLibrary{siunitx}\",\"\\\\NewTableCommand{\\\\tinytableDefineColor}[3]{\\\\definecolor{#1}{#2}{#3}}\",\"\\\\newcommand{\\\\tinytableTabularrayUnderline}[1]{\\\\underline{#1}}\",\"\\\\newcommand{\\\\tinytableTabularrayStrikeout}[1]{\\\\sout{#1}}\"]}]}]}"
      ]
    },
    "preserve": null,
    "postProcess": false
  }
}